kind: ConfigMap
apiVersion: v1
metadata:
  name: my-cnf
  namespace: cdc-cqrs-demo
data:
  my.cnf: |
    [mysqld]
    server-id=223344
    log_bin=mysql-bin
    binlog_format=ROW
    binlog_row_image=FULL
    expire_logs_days=3
    symbolic-links = 0
    skip_name_resolve
    ignore-db-dir=lost+found
    !includedir /etc/my.cnf.d
