apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: mongo-kafka-connect-cluster
  name: mongodb-sink-connector
  namespace: cdc-cqrs-demo
spec:
  class: com.mongodb.kafka.connect.MongoSinkConnector
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    topics: order_aggregate
    transforms: 'hk,hv'
    document.id.strategy.overwrite.existing: 'true'
    transforms.hk.field: _id
    document.id.strategy: com.mongodb.kafka.connect.sink.processor.id.strategy.ProvidedInKeyStrategy
    transforms.hv.type: org.apache.kafka.connect.transforms.HoistField$Value
    database: order_db
    transforms.hv.field: order
    connection.uri: 'mongodb://mjang:mjang@mongodb.cdc-cqrs-demo.svc.cluster.local:27017/order_db?authSource=order_db'
    transforms.hk.type: org.apache.kafka.connect.transforms.HoistField$Key
    collection: order
  tasksMax: 1
