apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: mongodb-connect-cluster
  name: mongodb-sink-connector
  namespace: cdc-cqrs-demo
spec:
  class: com.mongodb.kafka.connect.MongoSinkConnector
  config:
    value.converter: org.apache.kafka.connect.json.JsonConverter
    topics: order_aggregate
    transforms: 'hk,hv'
    document.id.strategy.overwrite.existing: 'true'
    value.converter.schemas.enable: false
    transforms.hk.renames: _id
    key.converter: org.apache.kafka.connect.storage.StringConverter
    document.id.strategy: com.mongodb.kafka.connect.sink.processor.id.strategy.ProvidedInKeyStrategy
    transforms.hv.type: org.apache.kafka.connect.transforms.HoistField$Value
    database: order_db
    transforms.hv.renames: order
    connection.uri: 'mongodb://mongodb.cdc-cqrs-demo.svc.cluster.local:27017'
    transforms.hk.type: org.apache.kafka.connect.transforms.HoistField$Key
    collection: order
  tasksMax: 1
