kind: KafkaConnector
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  labels:
    strimzi.io/cluster: debezium-kafka-connect-cluster
  name: source-connector-mysql
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    table.include.list: source-connector.*
    database.hostname: mysql.cdc-cqrs-demo.svc.cluster.local
    database.password: mjang
    topic.prefix: source-connector-mysql
    database.server.id: 223344
    database.port: 3306
    schema.history.internal.kafka.topic: schema-changes.source-connector
    database.user: mjang
    schema.history.internal.kafka.bootstrap.servers: 'cdc-cqrs-cluster-kafka-bootstrap.cdc-cqrs-demo.svc.cluster.local:9092'
    